api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("ingredients/", views.get_ingredients),
    path("subscriptions/", views.subscriptions),
    path("subscriptions/<int:author_id>", views.subscriptions_delete),
    path("favorites/", views.favorites),
    path("favorites/<int:recipe_id>", views.favorites_delete),
    path("purchases/", views.purchases),
    path("purchases/<int:recipe_id>", views.purchases_delete),

]

foodgramsite/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("about/", include("django.contrib.flatpages.urls")),
    path("about-food/", views.flatpage, {"url": "/about-food/"}, name="about"),
    path("about-spec/", views.flatpage, {"url": "/about-spec/"}, name="about-spec"), # noqa
    path(
        "about-author/", views.flatpage, {"url": "/about-author/"}, name="about-author" # noqa
    ),
    path("api/", include('api.urls')),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("recipes.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # noqa
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # noqa

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

handler404 = "recipes.views.page_not_found" # noqa
handler500 = "recipes.views.server_error" # noqa

recipes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("new_recipe/", views.new_recipe, name="new_recipe"),
    path(
        "<username>/<int:recipe_id>/edit/",
        views.recipe_edit,
        name="recipe_edit"
    ),
    path(
        "<username>/<int:recipe_id>/delete/",
        views.recipe_delete,
        name="recipe_delete"
    ),
    path("follow/", views.subscriptions_index, name="subscriptions_index"),
    path("favorite_recipe/", views.favorite_index, name="favorite_index"),
    path("shop_list/", views.shop_list, name="shop_list"),
    path(
        "shop_list/dowload/",
        views.dowload_shop_list,
        name="dowload_shop_list"
    ),
    path(
        "shop_list/<int:recipe_id>/",
        views.delete_recipe,
        name="delete_recipe"
    ),
    path("shop_list/", views.shop_list, name="shop_list"),

    path("<username>/", views.profile, name="profile"),
    path("<username>/<int:recipe_id>/", views.recipe_view, name="recipe"),
]

recipes/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Tag(models.Model):
    tag_options = {
        "breakfast": ["orange", "Завтрак"],
        "lunch": ["green", "Обед"],
        "dinner": ["purple", "Ужин"],
        "salads": ["red", "Салаты"],
    }

    TAG_CHOICES = [
        ("breakfast", "Завтрак"),
        ("lunch", "Обед"),
        ("dinner", "Ужин"),
        ("salads", "Салаты"),
    ]
    title = models.CharField(
        max_length=20, choices=TAG_CHOICES, verbose_name="Название тэга"
    )

    def __str__(self):
        return self.title

    @property
    def color(self):
        return self.tag_options[self.title][0]

    @property
    def name(self):
        return self.tag_options[self.title][1]


class Ingredient(models.Model):
    title = models.CharField(max_length=300, verbose_name="Название")
    dimension = models.CharField(max_length=20, verbose_name="Единица измерения") # noqa

    def __str__(self):
        return f"{self.title} {self.dimension}"


class Recipe(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="recipes",
        verbose_name="Автор публикации",
    )
    title = models.CharField(max_length=45, verbose_name="Название")
    image = models.ImageField(
        upload_to="recipes/", blank=True, verbose_name="Картинка"
    )
    description = models.TextField(verbose_name="Текстовое описание")
    pub_date = models.DateTimeField("data published", auto_now_add=True)
    tag = models.ManyToManyField(Tag, verbose_name="Тэг")
    ingredients = models.ManyToManyField(
        Ingredient,
        through="RecipeIngre",
        through_fields=("recipe", "ingredients"),
        verbose_name="Ингредиенты"
    )
    time = models.CharField(max_length=45, verbose_name="Время приготовления")

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.title


class RecipeIngre(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        verbose_name="Рецепты"
    )
    ingredients = models.ForeignKey(
        Ingredient, on_delete=models.CASCADE, verbose_name="Ингридиент"
    )
    count = models.FloatField()

    def __str__(self):
        return f"{self.recipe}"


class FollowUser(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Пользователь"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="Автор публикации"
    )

    def __str__(self):
        return self.user.username


class FollowRecipe(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower_recipe",
        verbose_name="Пользователь"
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name="following_recipe",
        verbose_name="Рецепт"
    )

    def __str__(self):
        return f"user - {self.user} recipe - {self.recipe}"


class ShoppingList(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="shop_list",
        verbose_name="Пользователь"
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name="shop_list",
        verbose_name="Список покупок"
    )

    def __str__(self):
        return self.recipe.title

recipes/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Recipe, RecipeIngre, Ingredient


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = (
            "title",
            "tag",
            "time",
            "description",
            "image",
        )
        widgets = {
            "tag": forms.CheckboxSelectMultiple(),
        }

    def clean(self):
        known_ids = []
        for items in self.data.keys():
            if 'nameIngredient' in items:
                name, id = items.split('_')
                known_ids.append(id)
        for id in known_ids:
            title = self.data.get(f'nameIngredient_{id}'),
            dimension = self.data.get(f'unitsIngredient_{id}')
            ingredient_exists = Ingredient.objects.filter(
                title=title[0],
                dimension=dimension,
            ).exists()
            if not ingredient_exists:
                raise ValidationError('Выберите ингредиент из списка!')


class RecipeIngreeForm(forms.ModelForm):
    class Meta:
        model = RecipeIngre
        fields = ("count",)

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Sum
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.conf import settings
from .utils import get_ingredients_from_js
from .forms import RecipeForm
from .models import (
    FollowUser,
    Ingredient,
    Recipe,
    RecipeIngre,
    ShoppingList,
    Tag,
    User,
)


def index(request):
    tags_values = request.GET.getlist("filters")
    recipe_list = Recipe.objects.all()

    if tags_values:
        recipe_list = recipe_list.filter(tag__title__in=tags_values).distinct().all() # noqa
    paginator = Paginator(recipe_list, settings.PAGE_SIZE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    tags = Tag.objects.all()
    return render(
        request,
        "index.html",
        {"page": page, "paginator": paginator, "tags": tags},
    )


@login_required
def new_recipe(request):
    tags = Tag.objects.all()
    recipe_form = RecipeForm(request.POST or None, files=request.FILES or None)
    if request.method == "POST":
        ingredients_req = get_ingredients_from_js(request)
        if not ingredients_req:
            recipe_form.add_error(None, "Добавьте ингредиенты")
        elif recipe_form.is_valid():
            recipe = recipe_form.save(commit=False)
            recipe.author = request.user
            recipe.save()
            for title, count in ingredients_req.items():
                ingredient = get_object_or_404(Ingredient, title=title)
                recipe_ingredient = RecipeIngre(
                    count=count, ingredients=ingredient, recipe=recipe
                )
                recipe_ingredient.save()
            recipe_form.save_m2m()
            return redirect("index")
    else:
        recipe_form = RecipeForm()
    return render(
        request,
        "form_recipe.html",
        {
            "form": recipe_form,
            "tags": tags,
        },
    )


@login_required
def recipe_edit(request, username, recipe_id):
    tags = Tag.objects.all()
    profile = get_object_or_404(User, username=username)
    recipe = get_object_or_404(Recipe, id=recipe_id, author=profile)
    if request.user != recipe.author:
        return redirect("recipe", username=request.user.username, recipe_id=recipe_id) # noqa
    if request.method == "POST":
        form = RecipeForm(
            request.POST or None, files=request.FILES or None, instance=recipe
        )
        ingredients_req = get_ingredients_from_js(request)
        if form.is_valid():
            RecipeIngre.objects.filter(recipe=recipe).delete()
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()
            for title, count in ingredients_req.items():
                ingredient = get_object_or_404(Ingredient, title=title)
                recipe_ingredient = RecipeIngre(
                    count=count, ingredients=ingredient, recipe=recipe
                )
                recipe_ingredient.save()
            form.save_m2m()
            return redirect("index")
    form = RecipeForm(
        request.POST or None, files=request.FILES or None, instance=recipe
    )

    return render(
        request,
        "form_change_recipe.html",
        {
            "form": form,
            "recipe": recipe,
            "tags": tags,
        },
    )


def profile(request, username):
    person = get_object_or_404(User, username=username)
    count_post = Recipe.objects.filter(author=person).count()
    post_list = (
        Recipe.objects.filter(author=person).select_related("author")
    )
    paginator = Paginator(post_list, settings.PAGE_SIZE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    author = User.objects.get(username=username)
    if request.user.is_authenticated:
        follow_status = FollowUser.objects.filter(user=request.user).filter(
            author=person
        )
        if not follow_status:
            follow_stat = None
        else:
            follow_stat = True
        return render(
            request,
            "author_recipe.html",
            {
                "page": page,
                "paginator": paginator,
                "username": username,
                "author": author,
                "count_post": count_post,
                "follow_stat": follow_stat,
            },
        )
    return render(
        request,
        "author_recipe.html",
        {
            "page": page,
            "paginator": paginator,
            "username": username,
            "author": author,
            "count_post": count_post,
        },
    )


def recipe_view(request, username, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    return render(request, "recipe.html", {"recipe": recipe})


@login_required
def subscriptions_index(request):
    authors_list = FollowUser.objects.select_related("user", "author").filter(
        user=request.user
    )
    paginator = Paginator(authors_list, settings.PAGE_SIZE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    return render(request, "my_follow.html", {"page": page, "paginator": paginator}) # noqa


@login_required
def favorite_index(request):
    tags_values = request.GET.getlist("filters")
    following_list = Recipe.objects.filter(
        following_recipe__user__id=request.user.id
    ).all()
    if tags_values:
        following_list = (
            following_list.filter(tag__title__in=tags_values).distinct().all()
        )
    paginator = Paginator(following_list, settings.PAGE_SIZE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    tags = Tag.objects.all()
    return render(
        request, "favorite.html", {"page": page, "paginator": paginator, "tags": tags} # noqa
    )


@login_required
def shop_list(request):
    shopList = Recipe.objects.filter(shop_list__user=request.user)
    return render(request, "shop_list.html", {"shopList": shopList})


@login_required
def delete_recipe(request, recipe_id):
    shop_recipe = get_object_or_404(ShoppingList, recipe_id=recipe_id)
    shop_recipe.delete()
    return redirect("shop_list")


@login_required
def dowload_shop_list(request):
    recipe = Recipe.objects.filter(shop_list__user=request.user)
    ingredients = (
        recipe.values("ingredients__title", "ingredients__dimension")
        .annotate(Sum("recipeingre__count"))
        .order_by()
    )
    content = "Список ингридиентов для приготовления выбранных блюд \n"
    for item in ingredients:
        title = item["ingredients__title"]
        count = item["recipeingre__count__sum"]
        dimension = item["ingredients__dimension"]
        content += f"{title} {count} {dimension}" + "\n"
    response = HttpResponse(content, content_type="text/plain")
    response["Content-Disposition"] = "attachment; filename=shopping-list.txt"
    return response


@login_required
def recipe_delete(request, username, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    recipe.delete()
    return redirect("index")


def page_not_found(request, exception):
    return render(request, "misc/404.html", {"path": request.path}, status=404)


def server_error(request):
    return render(request, "misc/500.html", status=500)

templates/authorRecipe.html
{% extends 'base.html' %}
{% block title %}Рецепты{% endblock %}
{% block content %}
{% load static %}
{% csrf_token %}
{% load user_filters %}

<link rel="stylesheet" href="{% static 'pages/index.css'%}">
<body class="body">
    <main class="main container">
           <div class="main__header">
            <h1 class="main__title">{{ author.username }}</h1>
            <ul class="tags">
                <li class="tags__item">
                    <a id="breakfast" class="tags__checkbox tags__checkbox_style_orange tags__checkbox_active" href="#"></a>
                    <span class="tags__label">Завтрак</span>
                </li>
                <li class="tags__item">
                    <a id="lunch" class="tags__checkbox tags__checkbox_style_green tags__checkbox_active" href="#"></a>
                    <span for="lunch" class="tags__label">Обед</span>
                </li>
                <li class="tags__item">
                    <a id="dinner" class="tags__checkbox tags__checkbox_style_purple tags__checkbox_active" href="#"></a>
                    <label for="dinner" class="tags__label">Ужин</label>
                </li>
                <li class="tags__item">
                    <a id="salads" class="tags__checkbox tags__checkbox_style_red tags__checkbox_active" href="#"></a>
                    <label for="salads" class="tags__label">Салаты</label>
                </li>
            </ul>
        </div>
        <div class="author-subscribe" data-author="{{ author.id }}">
            {% if user.is_authenticated %}
            {% if author|follow:request.user %}
            <p style="padding: 0 0 2em 0;">
                <button class="button button_style_light-blue button_size_auto" name="subscribe" >Отписаться от автора</button></p>
            {% else %}
              <p style="padding: 0 0 2em 0;">
                <button class="button button_style_light-blue button_size_auto" name="subscribe" data-out>Подписаться на автора</button></p>
            {% endif %}
        {% endif %}
        </div>
        <div class="card-list" >
            {% for recipe in page %}
            {% include "recipe_item.html" %}
        {% endfor %}
    </div>
    {% include "paginator.html"%}
    </main>
</body>

    {% block scripts %}
        <script src="{% static 'js/components/MainCards.js' %}"></script>

        <script src="{% static 'js/components/Purchases.js' %}"></script>
        <script src="{%static 'js/components/Favorites.js' %}"></script>
        <script src="{% static 'js/components/Subscribe.js' %}"></script>

        <script src="{% static 'js/config/config.js' %}"></script>
        <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
        <script src="{% static 'js/components/Header.js' %}"></script>

        <script src="{% static 'js/api/Api.js' %}"></script>
        <script src="{% static 'js/authorRecipe.js' %}"></script>

    {% endblock %}

{% endblock %}

templates/author_recipe.html
{% extends 'base.html' %}
{% block title %}Рецепты{% endblock %}
{% block content %}
{% load static %}
{% csrf_token %}
{% load user_filters %}

<link rel="stylesheet" href="{% static 'pages/index.css'%}">
<body class="body">
    <main class="main container">
           <div class="main__header">
            <h1 class="main__title">{{ author.username }}</h1>
            <ul class="tags">
                <li class="tags__item">
                    <a id="breakfast" class="tags__checkbox tags__checkbox_style_orange tags__checkbox_active" href="#"></a>
                    <span class="tags__label">Завтрак</span>
                </li>
                <li class="tags__item">
                    <a id="lunch" class="tags__checkbox tags__checkbox_style_green tags__checkbox_active" href="#"></a>
                    <span for="lunch" class="tags__label">Обед</span>
                </li>
                <li class="tags__item">
                    <a id="dinner" class="tags__checkbox tags__checkbox_style_purple tags__checkbox_active" href="#"></a>
                    <label for="dinner" class="tags__label">Ужин</label>
                </li>
                <li class="tags__item">
                    <a id="salads" class="tags__checkbox tags__checkbox_style_red tags__checkbox_active" href="#"></a>
                    <label for="salads" class="tags__label">Салаты</label>
                </li>
            </ul>
        </div>
        <div class="author-subscribe" data-author="{{ author.id }}">
            {% if user.is_authenticated %}
            {% if author|follow:request.user %}
            <p style="padding: 0 0 2em 0;">
                <button class="button button_style_light-blue button_size_auto" name="subscribe" >Отписаться от автора</button></p>
            {% else %}
              <p style="padding: 0 0 2em 0;">
                <button class="button button_style_light-blue button_size_auto" name="subscribe" data-out>Подписаться на автора</button></p>
            {% endif %}
        {% endif %}
        </div>
        <div class="card-list" >
            {% for recipe in page %}
            {% include "recipe_item.html" %}
        {% endfor %}
    </div>
    {% include "paginator.html"%}
    </main>
</body>

    {% block scripts %}
        <script src="{% static 'js/components/MainCards.js' %}"></script>

        <script src="{% static 'js/components/Purchases.js' %}"></script>
        <script src="{%static 'js/components/Favorites.js' %}"></script>
        <script src="{% static 'js/components/Subscribe.js' %}"></script>

        <script src="{% static 'js/config/config.js' %}"></script>
        <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
        <script src="{% static 'js/components/Header.js' %}"></script>

        <script src="{% static 'js/api/Api.js' %}"></script>
        <script src="{% static 'js/authorRecipe.js' %}"></script>

    {% endblock %}

{% endblock %}

templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock %} | Assistant product</title>
        <!-- Загрузка статики -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'pages/form.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'images/food-logo.png' %}" >
    </head>
    <body>
        {% include 'nav.html' %}
        <main>
            <div class="container">
                {% block content %}
                <!-- Содержимое страницы -->
                {% endblock content %}
            </div>
        </main>
        {% include 'footer.html' %}
    </body>
</html>

templates/favorite_button.html
{% load user_filters %}

{% if user.is_authenticated %}
    {% if recipe|favorite:user %}
        <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
    {% else %}
        <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
    {% endif %}
{% endif %}

templates/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="/about-food/" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="/about-author/" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="/about-spec/" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

templates/index.html
{% extends 'base.html' %}
{% block title %}Рецепты{% endblock %}
{% block content %}
{% load static %}
{% csrf_token %}
{% load user_filters %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Рецепты</title>
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
</head>
<body class="body">
<header class="header">
</header>
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Рецепты</h1>
            {% include "tags.html"%}
            </div>
        <div class="card-list">
        {% for recipe in page %}
        {% include "recipe_item.html" %}
        {% endfor %}
    </div>
        {% include "paginator.html"%}
    </main>
</body>
</html>
    {% block scripts %}
    {% if user.is_authenticated %}
    <script src="{% static 'js/components/MainCards.js'%}"></script>

    <script src="{% static 'js/components/Purchases.js'%}"></script>
    <script src="{% static 'js/components/Favorites.js'%}"></script>
  
    <script src="{% static 'js/config/config.js'%}"></script>
    <script src="{% static 'js/components/CardList.js'%}"></script>
    <script src="{% static 'js/components/Header.js'%}"></script>
  
    <script src="{% static 'js/api/Api.js'%}"></script>
    <script src="{% static 'js/indexAuth.js'%}"></script>

    {% else %}



    <script src="{% static 'js/components/MainCards.js'%}"></script>

    <script src="{% static 'js/components/Purchases.js'%}"></script>

    <script src="{% static 'js/config/config.js'%}"></script>
    <script src="{% static 'js/components/CardList.js'%}"></script>
    <script src="{% static 'js/components/Header.js'%}"></script>

    <script src="{% static 'js/api/Api.js'%}"></script>
    <script src="{% static 'js/indexNotAuth.js'%}"></script>
    {% endif %}
    {% endblock %}
    

{% endblock %}

templates/nav.html
<header class="header"></header>
<nav class="nav">
    {% with url_name=request.resolver_match.url_name %}
    {% if user.is_authenticated %}
    <div class="nav__container container">
        
        <ul class="nav__items list">
            <li class="nav__item {% if url_name == 'index' %} nav__item_active {% endif %}"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
            <li class="nav__item {% if url_name == 'subscriptions_index' %} nav__item_active {% endif %}"><a href="{% url 'subscriptions_index' %}" class="nav__link link">Мои подписки</a></li>
            <li class="nav__item {% if url_name == 'new_recipe' %} nav__item_active {% endif %}"><a href="{% url 'new_recipe' %}" class="nav__link link">Создать рецепт</a></li>
            <li class="nav__item {% if url_name == 'favorite_index' %} nav__item_active {% endif %}"><a href="{% url 'favorite_index' %}" class="nav__link link">Избранное</a></li>
            <li class="nav__item {% if url_name == 'shop_list' %} nav__item_active {% endif %}"><a href="{% url 'shop_list' %}" class="nav__link link">Список покупок</a> <span class="badge badge_style_blue nav__badge" id="counter">{% if user.shop_list.count > 0 %}{{ user.shop_list.count }}{% endif %}</span></li>
            
        </ul>
        <ul class="nav__items list">
            <li class="nav__item {% if url_name == 'password_change' %} nav__item_active {% endif %}"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
            <li class="nav__item {% if url_name == 'logout' %} nav__item_active {% endif %}"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
        </ul>
    </div>
    {% else %}
    <div class="nav__container container">
        <ul class="nav__items list">
            <li class="nav__item {% if url_name == 'index' %} nav__item_active {% endif %}"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
        </ul>
        <ul class="nav__items list">
            <li class="nav__item {% if url_name == 'login' %} nav__item_active {% endif %}"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
            <li class="nav__item {% if url_name == 'signup' %} nav__item_active {% endif %}"><a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
        </ul>
    </div>
    {% endif %}
    {% endwith %}
</nav>
</header>

templates/recipe.html
{% extends 'base.html' %}
{% block title %}Рецепты{% endblock %}
{% block content %}
{% load static %}
{% csrf_token %}
{% load user_filters %}

<link rel="stylesheet" href="{% static 'pages/single.css'%}">
    <main class="main container">
        <div class="single-card" data-id="{{ recipe.id }}" data-author="{{ recipe.author.id }}">
            {% load thumbnail %}
            {% thumbnail recipe.image "600x600" as im %}
            <img src="{{ im.url }}" alt="какой-то текст" class="single-card__image">
            {% endthumbnail %} 
            <div class="single-card__info">
                <div class="single-card__header-info">
                    <h1 class="single-card__title"> {{ recipe.title }}</h1>
                    <div class="single-card__favorite">
                        {% include "favorite_button.html" %}
                        <div class="single-card__favorite-tooltip tooltip">Добавить в избранное</div>
                    </div>
                </div>
                <ul class="single-card__items">
                    {% for tag in recipe.tag.all %}
                        <li class="single-card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag.name }}</span></li>
                    {% endfor %}
                </ul>
                <div class="single-card__items single-card__items_column">
                    <p class="single-card__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
                    <ul class="single-card__items">
                        <li class="single-card__item"><p class="single-card__text"><span class="icon-user" ></span> {{ recipe.author }}</p></li>
                        {% if user == recipe.author %}
                        <li class="single-card__item">  <a style="margin-left: 2.5em" href="{% url 'recipe_edit' recipe.author.username recipe.id %}" class="single-card__text">Редактировать рецепт</a></li>
                       
                        {% endif %}
                    </ul>
                </div>
                <ul class="single-card__items">
                    <li class="single-card__item">{% include "shop_list_button.html" %}</li>
                {% if user.is_authenticated %}
                    {% if recipe.author|follow:user %}
                    <li class="single-card__item"><button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться от автора</button></li>
                    {% else %}
                    <li class="single-card__item"><button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button></li>
                    {% endif %}
                {% endif %}
                </ul>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Ингридиенты:</h3>
                    <div class="single-card__items single-card__items_column">
                        {% for ingredient in recipe.recipeingre_set.all %}
                        <p class=" single-card__section-item">{{ingredient.ingredients}} - {{ingredient.count}} {{ingredient.ingredients.dimension}}.</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Описание:</h3>
                    <p class=" single-card__section-text">{{ recipe.description}}</p>
                </div>
            </div>
        </div>
    </main>

{% if user.is_authenticated %}
    <script src="{% static 'js/components/Purchases.js'%}"></script>
    <script src="{% static 'js/components/Favorites.js'%}"></script>
    <script src="{% static 'js/components/Subscribe.js'%}"></script>
    <script src="{% static 'js/config/config.js'%}"></script>

    <script src="{% static 'js/components/MainCards.js'%}"></script>
    <script src="{% static 'js/components/SingleCard.js'%}"></script>
    <script src="{% static 'js/components/Header.js'%}"></script>

    <script src="{% static 'js/api/Api.js'%}"></script>
    <script src="{% static 'js/singlePage.js'%}"></script>
{% else %}
    <script src="{% static 'js/components/Purchases.js'%}"></script>
    <script src="{% static 'js/config/config.js'%}"></script>

    <script src="{% static 'js/components/MainCards.js'%}"></script>
    <script src="{% static 'js/components/SingleCard.js'%}"></script>
    <script src="{% static 'js/components/Header.js'%}"></script>

    <script src="{% static 'js/api/Api.js'%}"></script>
    <script src="{% static 'js/singlePageNotAuth.js'%}"></script>
    {% endif %}
{% endblock %}